on:
  push:
  #  branches:
  #    - master
  pull_request:
    branches:
      - master

name: build_check_deploy

jobs:
  build_check_deploy:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories(), Ncpu = 2L)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Install TeX-related dependencies 
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texinfo

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "error", check_dir = "check")
        shell: Rscript {0}
